Replaced UWS with WS because Craig was looking for WS not UWS.
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- /home/concord/concord/craig/rec.js
- /home/concord/concord/craig.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/concord/concord/craig/rec.js:28:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/concord/concord/craig/rec.js',
    '/home/concord/concord/craig.js'
  ]
}